name: somenet
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  provider: ^6.1.2
  pin_code_fields: ^8.0.1
  equatable: ^2.0.5
  sizer: ^3.0.0
  image_picker: ^1.1.2
  http: ^1.2.2
  json_annotation: ^4.9.0
  flutter_secure_storage: ^4.2.1
  flutter_advanced_drawer: ^1.3.6
  flutter_localization: ^0.2.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  intl_utils: ^2.8.7
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  flutter_intl: ^0.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  # flutter_intl configuration
flutter_intl:
  enabled: true
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-class: AppLocalizations
  output-localization-file: app_localizations.dart
