const applogo = "assets/images/applogo.png";
const homescreenBanner = "assets/images/homescreen banner.png";
const profileimage = "assets/images/profieimage.png";
const buybunldelistnormallogo = "assets/images/Vector.png";
const myvasListIcon = "assets/images/myvaslisticon.png";
const selfsupportkey = "assets/images/selfsupport_key.png";
const customfeedbackIcon = "assets/images/customfeedbackicon.png";
const ticketicon = "assets/images/ticket.png";
const inviteafriendIcon = "assets/images/ivite a frinedicon.png";
